### ISSUE TITLE
TCC, CL(VS), GCC issues with basic demo

### ISSUE THREAD

**Issue by KeyWeeUsr** [vurtun/nuklear#357]
I can't compile even the basic example from the Readme.md. Any ideas why? I think TCC was closest to actually compiling it, but there is an issue with `sizeof(void*)`. The only wrong code I found was [this](http://stackoverflow.com/q/1666224/5994041), which is just `void`, not a `void` pointer, therefore I think that code isn't really an issue and I need to set something in TCC, so that it accepts [`void` pointer size](http://stackoverflow.com/a/3853329/5994041).

The rest, however, returns just crap, especially CL. So... I wonder what am I doing wrong?

Also, if you don't do support on GitHub, feel free to give me pointers where you do, as I didn't find anything on [StackOverflow](http://stackoverflow.com/questions/tagged/nuklear).

## example:

```c
#include <stdio.h>
#include <stdlib.h>
#define NK_IMPLEMENTATION
#include "nuklear.h"
/* init gui state */
struct nk_context ctx;
nk_init_fixed(&ctx, calloc(1, MAX_MEMORY), MAX_MEMORY, &font);

enum {EASY, HARD};
int op = EASY;
float value = 0.6f;
int i =  20;

if (nk_begin(&ctx, "Show", nk_rect(50, 50, 220, 220),
    NK_WINDOW_BORDER|NK_WINDOW_MOVABLE|NK_WINDOW_CLOSABLE)) {
    /* fixed widget pixel width */
    nk_layout_row_static(&ctx, 30, 80, 1);
    if (nk_button_label(&ctx, "button")) {
        /* event handling */
    }

    /* fixed widget window ratio width */
    nk_layout_row_dynamic(&ctx, 30, 2);
    if (nk_option_label(&ctx, "easy", op == EASY)) op = EASY;
    if (nk_option_label(&ctx, "hard", op == HARD)) op = HARD;

    /* custom widget pixel width */
    nk_layout_row_begin(&ctx, NK_STATIC, 30, 2);
    {
        nk_layout_row_push(&ctx, 50);
        nk_label(&ctx, "Volume:", NK_TEXT_LEFT);
        nk_layout_row_push(&ctx, 110);
        nk_slider_float(&ctx, 0, &value, 1.0f, 0.1f);
    }
    nk_layout_row_end(&ctx);
}
nk_end(&ctx);
```

## GCC 4.9.2

> gcc 01.c -Wall
```
01.c:7:15: error: expected declaration specifiers or '...' before '&' token
 nk_init_fixed(&ctx, calloc(1, MAX_MEMORY), MAX_MEMORY, &font);
               ^
01.c:7:21: error: expected declaration specifiers or '...' before 'calloc'
 nk_init_fixed(&ctx, calloc(1, MAX_MEMORY), MAX_MEMORY, &font);
                     ^
01.c:7:44: error: unknown type name 'MAX_MEMORY'
 nk_init_fixed(&ctx, calloc(1, MAX_MEMORY), MAX_MEMORY, &font);
                                            ^
01.c:7:56: error: expected declaration specifiers or '...' before '&' token
 nk_init_fixed(&ctx, calloc(1, MAX_MEMORY), MAX_MEMORY, &font);
                                                        ^
01.c:14:1: error: expected identifier or '(' before 'if'
 if (nk_begin(&ctx, "Show", nk_rect(50, 50, 220, 220),
 ^
01.c:37:8: error: expected declaration specifiers or '...' before '&' token
 nk_end(&ctx);
        ^
In file included from 01.c:4:0:
nuklear.h:3234:1: warning: 'nk_sqrt' defined but not used [-Wunused-function]
 nk_sqrt(float x)
 ^
nuklear.h:3240:1: warning: 'nk_sin' defined but not used [-Wunused-function]
 nk_sin(float x)
 ^
nuklear.h:3254:1: warning: 'nk_cos' defined but not used [-Wunused-function]
 nk_cos(float x)
 ^
nuklear.h:3888:1: warning: 'nk_ifloorf' defined but not used [-Wunused-function]

 nk_ifloorf(float x)
 ^
```

## TCC

> tcc 01.c -o 01.exe -Wall
```
In file included from 01.c:4:
nuklear.h:420: error: invalid array size
```

## CL(Visual Studio C++ Build Tools 14.0)

> cl 01.c
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

01.c
01.c(7): error C2143: syntax error: missing ')' before '&'
01.c(7): error C2143: syntax error: missing '{' before '&'
01.c(7): error C2059: syntax error: '&'
01.c(14): error C2059: syntax error: 'if'
01.c(37): error C2143: syntax error: missing ')' before '&'
01.c(37): error C2143: syntax error: missing '{' before '&'
01.c(37): error C2059: syntax error: '&'
01.c(37): error C2059: syntax error: ')'
```

**Comment by dumblob** [comment]
Where is `main()`?

**Comment by KeyWeeUsr** [comment]
Well, this is embarrassing... 🙍 

Anyway, now it at least returns a usable error!

```
01.c
01.c(8): error C2065: 'MAX_MEMORY': undeclared identifier
01.c(8): error C2065: 'font': undeclared identifier
01.c(8): warning C4133: 'function': incompatible types - from 'int *' to 'const nk_user_font *'
```

**Comment by vurtun** [comment]
Hey thanks for your issue. Did you try any of the provided demo backends (can be found inside the `demo/` directory). The example from the `Readme` does not work on its own. It only describes the basic usage of the UI library portion. However if you combine it with one of the demo backends everything just works out of the box.

**Comment by dumblob** [comment]
>Well, this is embarrassing...

Who hasn't experienced such issues can't be a real programmer :wink:.

Go for the `/demo`s and `/example`s as @vurtun suggested.

**Comment by KeyWeeUsr** [comment]
I knew there's some catch with a single file gui, especially with C. :D Anyway, I'll try the demos when I'll have more time (no headers except sdl2 and GL), but the `/example` seems to return a separator issue with Visual Studio's `nmake.exe`:

```
makefile(3) : fatal error U1033: syntax error : '=' unexpected
Stop.
```

With the rest there's just a simple problem and that is missing Windows' alternative to `rm`(it's `del` or `rmdir`). I'll try to make a PR if I get it to work. ^^

For now I get just some linking errors for GL or closely related libs, so I'll need to find the necessary headers and compile again. Thanks for your help :)

**Comment by vurtun** [comment]
> I knew there's some catch with a single file gui, especially with C

Well one single header for the actual UI + optional stuff and one additional header for each platform this library supports is hopefully survivable.

**Comment by KeyWeeUsr** [comment]
I just hoped most of it (if not all) would be already in the compiler's includes. It's not a con though, I just didn't have the environment prepared. :)

**Comment by vurtun** [comment]
If it is a problem you can just copy your platform of choice directly into `nuklear.h`. The main reason why ui and platform code is separated is not to pollute the ui code and force everyone to pull code into their project they don't need.
